In [2]:
import numpy as np # Import numpy

In [7]:
arrayOfOnes = np.ones(5)

In [8]:
arrayOfOnes # An array of 5 1s

array([1., 1., 1., 1., 1.])

In [11]:
arrayOfZeros = np.zeros(5)

In [12]:
arrayOfZeros # An array of 5 0s

array([0., 0., 0., 0., 0.])

In [13]:
arrayOfEvens = np.arange(2,100,2)

In [14]:
arrayOfEvens # An array of even numbers between 2 and 100

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34,
       36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66, 68,
       70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98])

In [18]:
arrayOfTens = np.ones(5) * 10

In [19]:
arrayOfTens # An array of 5 10s

array([10., 10., 10., 10., 10.])

In [21]:
array1 = np.arange(1,17)
array1 = array1.reshape(4,4)
array1 # A 4x4 matrix of numbers from 1 to 16

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [22]:
array2 = np.eye(4)
array2 # 4x4 unit matrix

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [28]:
number1 = np.random.randint(5)
number1

4

In [32]:
array3 = np.random.randn(25)
array3 = array3.reshape(5,5)
array3 # A 5x5 matrix with Gaussian distribution

array([[ 1.32025796,  0.09543299, -0.61061419,  0.18344912, -0.68719305],
       [-0.55673758, -0.20203119,  0.85403589,  0.17562476, -0.22942266],
       [ 1.00689996, -1.31561016,  0.51411142, -0.67042973, -0.31762815],
       [-1.615088  ,  1.94839296, -1.19917728, -1.1767387 ,  0.51640518],
       [-0.74451103,  1.04980427,  0.80536941, -0.22761697,  1.28481389]])

In [33]:
array4 = np.linspace(1,5,20)
array4 # The array formed by dividing the numbers 1 to 5 into 20 equal parts

array([1.        , 1.21052632, 1.42105263, 1.63157895, 1.84210526,
       2.05263158, 2.26315789, 2.47368421, 2.68421053, 2.89473684,
       3.10526316, 3.31578947, 3.52631579, 3.73684211, 3.94736842,
       4.15789474, 4.36842105, 4.57894737, 4.78947368, 5.        ])

In [34]:
array5 = np.arange(1,101).reshape(10,10)
array5

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [36]:
array5[4:, :]

array([[ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [37]:
array5[6:, 4:]

array([[ 65,  66,  67,  68,  69,  70],
       [ 75,  76,  77,  78,  79,  80],
       [ 85,  86,  87,  88,  89,  90],
       [ 95,  96,  97,  98,  99, 100]])

In [38]:
array5[0:3, 2:4]

array([[ 3,  4],
       [13, 14],
       [23, 24]])

In [39]:
array5[:3, 1]

array([ 2, 12, 22])

In [40]:
array5[:, -1]

array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

In [41]:
array6 = ((np.random.rand(9) * 5).astype(int)).reshape(3,3)
array7 = ((np.random.rand(9) * 5).astype(int)).reshape(3,3)

In [42]:
array6

array([[1, 4, 3],
       [4, 0, 3],
       [1, 1, 0]])

In [43]:
array7

array([[0, 4, 0],
       [2, 1, 1],
       [2, 1, 0]])

In [44]:
array6 + array7 # Sum of two matrix

array([[1, 8, 3],
       [6, 1, 4],
       [3, 2, 0]])

In [45]:
array6 * array7 # Product of two matrix

array([[ 0, 16,  0],
       [ 8,  0,  3],
       [ 2,  1,  0]])

In [46]:
array6.mean() # Mean of elements of array6

1.8888888888888888

In [47]:
array7.sum() # Sum of elements of array7

11